Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/trusty64"

	#2048 MB RAM + 2 CPUs, change if needed
	config.vm.provider "virtualbox" do |v|
	  v.name = "(CI) Jenkins + Arachni Security Scanner + WAVSEP"
	  v.memory = 2048
	  v.cpus = 2
	end

	config.vm.provider "virtualbox" do |v|
		#SSH
		config.vm.network :forwarded_port, guest: 22, host: 2202, host_ip: "127.0.0.1"
		
		#Jenkins
		config.vm.network :forwarded_port, guest: 8181, host: 8181, host_ip: "127.0.0.1"
		
		#WAVSEP (Tomcat)
		config.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "127.0.0.1"
		
		#Host Only Adapter
		config.vm.network "private_network", ip: "192.168.56.102", :name => 'vboxnet0', :adapter => 2
	end

	config.vm.provision "shell" do |s|
		s.path = "provision/vagrant-ci-provision.sh"
		s.privileged = false
	end

end